listen = *
protocols = imap

disable_plaintext_auth = no
auth_mechanisms = plain login
mail_privileged_group = mail
mail_location = mbox:~/mail:INBOX=/var/mail/%u

log_path = /var/log/mail/dovecot.log
info_log_path = /var/log/mail/dovecot-info.log

passdb {
  driver = pam
}

userdb {
  driver = passwd
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

ssl = no
